### ISSUE TITLE
[S] To-do list (v0.2)

### ISSUE THREAD

**Issue by petrveprek** [petrveprek/scribo#13]
Next **major**
- Must
- Should
- May

Next **minor**
- Must
  - [x] Add CHANGELOG.md (starting from v0.1 2015/6/6 ...) --> check .gitattributes for *.md
  - [x] Put .dummy(?) into object/ to include the "empty" folder in scribo package, needed by makefile
- Should
  - [x] Add hotlinks to README.md: to LICENSE file; to "see Specification..."
  - [x] Add all-you-need-to-know
- May
  - [ ] Add IF_SCRIBO
  - [x] Flush
  - [ ] Config: suppress: timestamp, msg counter, category, verbosity, newline
  - [ ] Config: do not flush

Next **hotfix**
- Must
- Should
- May

Not-planned
- Must
- Should
- May
