### ISSUE TITLE
[S] To-do list (v0.3)

### ISSUE THREAD

**Issue by petrveprek** [petrveprek/scribo#16]
Next **major**
- Must
- Should
- May

Next **minor**
- Must
  - [x] Config: suppress: timestamp, msg counter, category, verbosity, newline
  - [x] Config: do not flush
  - [x] Make getting 'now' conditional only when needed
  - [x] Update spec (have "what" to log, add "how" it looks)
  - [x] Use SCRIBO after "if()..." in an example
- Should
  - [ ] Custom sink/destination/callback (either ("format", ...) or ("text"))
  - [ ] Auto-generate trace log message
  - [ ] Auto-generate method (entry/exit) log message
- May
  - [ ] Add IF_SCRIBO
  - [ ] C++ example w/ makefile

Next **hotfix**
- Must
- Should
- May

Not-planned
- Must
- Should
  - [ ] Create _scribo rt_
  - [ ] Create _scribo af_
- May
  - [ ] Dynamic category
  - [ ] Dynamic verbosity
