### ISSUE TITLE
[S] To-do list (v0.4)

### ISSUE THREAD

**Issue by petrveprek** [petrveprek/scribo#18]
Next **major**
- Must
- Should
- May

Next **minor**
- Must
  - [x] Custom sink/destination/callback (either ("format", ...) or ("text"))
- Should
  - [ ] Add comments
  - [ ] Auto-generate trace log message
  - [ ] Auto-generate method (entry/exit) log message
  - [ ] Profile: time & memory per log line
- May
  - [ ] Add IF_SCRIBO
  - [ ] Add examples

Next **hotfix**
- Must
- Should
- May

Not-planned
- Must
- Should
  - [ ] C++ example w/ makefile
  - [ ] Create _scribo rt_ (run time)  [run time control, generation...]
  - [ ] Create _scribo af_ (advanced features) [post mortem...]
  - [ ] Create _scribo le_ (light edition) [only category & verbosity]
  - [ ] Create _scribo ??++_ (?? C++) [OO style]
- May
  - [ ] Dynamic category
  - [ ] Dynamic verbosity
