### ISSUE TITLE
[S] To-do list (v0.5)

### ISSUE THREAD

**Issue by petrveprek** [petrveprek/scribo#20]
Next **major**
- Must
- Should
- May

Next **minor**
- Must
  - [x] Auto-generate trace log message
  - [x] Auto-generate method (entry/exit) log message
- Should
  - [x] Review and add comments
  - [ ] Profile: time & memory per log line
- May
  - [ ] Add IF_SCRIBO
  - [x] Add examples

Next **hotfix**
- Must
- Should
- May

Not-planned
- Must
- Should
  - [ ] C++ example w/ makefile
  - [ ] Create _scribo rt_ (run time)  [run time control, generation...]
  - [ ] Create _scribo af_ (advanced features) [post mortem...]
  - [ ] Create _scribo le_ (light edition) [only category & verbosity]
  - [ ] Create _scribo ??++_ (?? C++) [OO style]
- May
  - [ ] Dynamic category
  - [ ] Dynamic verbosity
