### ISSUE TITLE
[S] To-do list (v0.6)

### ISSUE THREAD

**Issue by petrveprek** [petrveprek/scribo#22]
Next **major**
- Must
  - [ ] Test functionality
  - [ ] Review documentation
- Should
- May

Next **minor**
- Must
  - [x] Add auto-fill configuration
  - [x] Update documentation
- Should
  - [x] Review and add comments
  - [ ] Profile: time & memory per log line
- May
  - [ ] Default verbosity to DEBUG
  - [ ] Add IF_SCRIBO
  - [ ] Add examples

Next **hotfix**
- Must
- Should
- May

Not-planned
- Must
- Should
  - [ ] C++ example w/ makefile
  - [ ] Create _scribo rt_ (run time)  [run time control, generation...]
  - [ ] Create _scribo af_ (advanced features) [post mortem...]
  - [ ] Create _scribo le_ (light edition) [only category & verbosity]
  - [ ] Create _scribo ??++_ (?? C++) [OO style]
- May
  - [ ] Dynamic category
  - [ ] Dynamic verbosity
