### ISSUE TITLE
[S] To-do list (v1.0)

### ISSUE THREAD

**Issue by petrveprek** [petrveprek/scribo#26]
Next **major**
- Must
  - [x] Test functionality
  - [x] Review documentation
- Should
- May

Next **minor**
- Must
- Should
  - [x] Append newline for trimmed messages
- May
  - [ ] Add IF_SCRIBO
  - [ ] Profile: time & memory per log line

Next **hotfix**
- Must
- Should
- May

Not-planned
- Must
- Should
  - [ ] C++ example w/ makefile
  - [ ] Create _scribo rt_ (run time)  [run time control, generation...]
  - [ ] Create _scribo af_ (advanced features) [post mortem...]
  - [ ] Create _scribo le_ (light edition) [only category & verbosity]
  - [ ] Create _scribo ??++_ (?? C++) [OO style]
- May
  - [ ] Dynamic category
  - [ ] Dynamic verbosity
