### ISSUE TITLE
[S] To-do list (v1.1)

### ISSUE THREAD

**Issue by petrveprek** [petrveprek/scribo#28]
Next **major**
- Must
- Should
- May

Next **minor**
- Must
  - [x] Create _scribo le_ (light edition) [only category & verbosity]
  - [x] Correct auto-fill for FATAL in README.md
- Should
- May

Next **hotfix**
- Must
- Should
- May

Not-planned
- Must
- Should
  - [ ] C++ example w/ makefile
  - [ ] Create _scribo rt_ (run time)  [run time control, generation...]
  - [ ] Create _scribo af_ (advanced features) [post mortem...]
  - [ ] Create _scribo ??++_ (?? C++) [OO style]
- May
  - [ ] Add IF_SCRIBO
  - [ ] Profile: time & memory per log line
  - [ ] Dynamic category
  - [ ] Dynamic verbosity
