### ISSUE TITLE
[S] To-do list (v1.2)

### ISSUE THREAD

**Issue by petrveprek** [petrveprek/scribo#30]
Next **major**
- Must
- Should
- May

Next **minor**
- Must
  - [x] Rename identifiers with adjacent underscores
  - [x] Add EXEQUI
  - [x] Update README.md
- Should
- May

Next **hotfix**
- Must
- Should
- May

Not-planned
- Must
- Should
  - [ ] C++ example w/ makefile
  - [ ] Create _scribo rt_ (run time)  [run time control, generation...]
  - [ ] Create _scribo af_ (advanced features) [post mortem...]
  - [ ] Create _scribo ??++_ (?? C++) [OO style]
- May
  - [ ] Add IF_SCRIBO
  - [ ] Add SUPPRESS_MESSAGE_HEADER
  - [ ] Add "log every n-th"
  - [ ] Add "log first n"
  - [ ] Add "log after n"
  - [ ] Add milliseconds to timestamp
  - [ ] Profile: time & memory per log line
  - [ ] Dynamic category
  - [ ] Dynamic verbosity
